### ISSUE TITLE
how to run?

### ISSUE THREAD

**Issue by datNoko** [Chimrod/i3_workspaces#1]
Hi, i have installed i3 workspaces and created the config file. How do i actually use it? It will not work out of the box apparently.

**Comment by Chimrod** [comment]
It should :)

can you edit the line `on_focus` and set `on_focus=echo feh --bg-fill ${image}` then navigate through the workspaces ?

You should have a similar output in the console :

```
$ i3_workspaces -- -c config 
feh --bg-fill /home/sebastien/wallpaper/i3_wallpapers/5.jpg
Unknown workspace 51:
Unknown workspace 51:
feh --bg-fill /home/sebastien/wallpaper/i3_wallpapers/default.jpg
```

**Comment by Chimrod** [comment]
There is a typo in the readme : it should be bg-scale and not `bg scale` in the example. This may be your problem ?

**Comment by datNoko** [comment]
with "i3_workspaces -- -c config" i get the output "command not found"

**Comment by Chimrod** [comment]
After the compilation, the binary should be in `_build/default/src/i3_workspaces.exe`

So can you try `_build/default/src/i3_workspaces.exe -c config` ?

**Comment by datNoko** [comment]
ok thanks it worked after manually executing "_build/default/src/i3 workspaces.exe"

**Comment by Chimrod** [comment]
I've added an install target in the makefile which will install the binary in `/usr/bin` this should help future users

Thanks for your report !
