### ISSUE TITLE
Release compiled binaries?

### ISSUE THREAD

**Issue by hyiltiz** [Chimrod/i3_workspaces#4]
It doesn't have to be .deb or .rpm packages etc. Is it possible to build a single binary that can then be downloaded into `~/bin/` and run? I'd love to try this out (been using i3 for over 5 years and am very happy so far), but would rather not pull down the whole OCaml dependency just to build it. I wonder if many potential users share this concern.

**Comment by Chimrod** [comment]
Hello,

I've published a release with the package for debian and redhat. The binary is statically linked, and should be run on any system with amd64 architecture.

https://github.com/Chimrod/i3_workspaces/releases/tag/v0.2

**Comment by hyiltiz** [comment]
Just installed it. I wanted to try the binary bisection with a mouse displayed as a gif in the project front page. I called `i3 workspaces` which I think just called `i3` with the argument `workspace s`. I called `/opt/i3_workspaces/i3_workspaces` which said `Configuration file  not found`. Maybe install with a minimal default configuration file so it while it doesn't auto-assign anything, it still has some functionality? Anyway, I installed the config:
```
[global]
layout=binary
```
and ran it. But I couldn't figure out how to do the bisection; clicking with mouse while holding a few modifiers I tried didn't work.

**Comment by Chimrod** [comment]
Where did you put the file ? By default, it is read in `${XDG_CONFIG_HOME}/i3_workspaces/config` but you can specify any other location by invoking the command with `i3_workspaces -c path/to/the/file`

Maybe should you run i3_workspace from a terminal in order to check if everything work fine in a first step.

The bisection is applied each time you open a new window : try opening some terminals (`$mod+Enter` by default in i3) to see them opening in a binary tree.

**Comment by hyiltiz** [comment]
I put it at `${XDG_CONFIG_HOME}/i3_workspaces/config`, specifically `~/.config/i3_workspaces/config`. I did run it from a terminal by calling `/opt/i3_workspaces/i3_workspaces`. Without the config it asked me to config it; once the config was in place, it was responding to my workspace actions by printing the names of the workspace.

I managed to make the bisection work; my workspaces were by default in the tabbed mode; I just had to press `mod+a` to focus parent first.

**Comment by Chimrod** [comment]
You're right I do not manage the differents layout stacked, tabbed…

Have fun :)

Can I close the ticket ?

**Comment by hyiltiz** [comment]
Thx for the info! It may be helpful if the readme was slightly more detailed so users may know how to use and what to expect. Cool project in a cool language!

**Comment by Chimrod** [comment]
I've opened the issue #5 for thoses cases. As I do not uses thoses myself, I have to build the layout and check if I do not break the tree by applying the transformations.

Does the tool suits your needs in the actual version ?

**Comment by hyiltiz** [comment]
Thx for opening the new issue! I haven't really went on to translate my two dozen for_window rules yet, so cannot tell yet how this tool suit my needs. It could make my i3 config much more simplified.
